import { Category, Product } from '@/types';

export const FB_PROFILE_URL = 'https://www.facebook.com/profile.php?id=61594225684008';
export const MESSENGER_URL = 'https://m.me/61594225684008';

export const CATEGORIES: Category[] = [
  {
    id: 'hijab',
    name: 'Prayer Hijabs',
    banglaName: 'নামাজের হিজাব',
    slug: 'hijab',
    image: '/images/products/prayer-hijab-all-1.jpg',
    description: 'খাঁটি বেক্সি বয়েল কাপড়ে তৈরি আরামদায়ক ও ব্রিদেবল নামাজের হিজাব',
  },
  {
    id: 'inner-cap',
    name: 'Lace Inner Caps',
    banglaName: 'লেইস ইনার ক্যাপ',
    slug: 'inner-cap',
    image: '/images/products/inner-cap-lace.jpg',
    description: 'বাতাস চলাচল-উপযোগী প্রসারনযোগ্য লেইসের ইনার ক্যাপ',
  },
  {
    id: 'hijab-pins',
    name: 'Hijab Pins',
    banglaName: 'হিজাব পিন',
    slug: 'hijab-pins',
    image: '/images/products/hijab-pins.jpg',
    description: 'প্রিমিয়াম স্টেইনলেস স্টিল বল হেড হিজাব পিন',
  },
];

export const PRODUCTS: Product[] = [
  // --- Category: HIJAB (Colorwise) ---
  {
    id: 'tiara-prayer-hijab-lavender',
    name: 'Bexi Boil Prayer Hijab - Lavender',
    banglaName: 'বেক্সি বয়েল নামাজের হিজাব - ল্যাভেন্ডার',
    slug: 'bexi-boil-prayer-hijab-lavender',
    category: 'hijab',
    price: 550,
    originalPrice: 650,
    images: [
      '/images/products/prayer-hijab-lavender.jpg',
      '/images/products/prayer-hijab-all-1.jpg',
      '/images/products/prayer-hijab-all-2.jpg',
    ],
    description: 'খাঁটি বেক্সি বয়েল (Bexi boil) কাপড় দিয়ে তৈরি বাতাস চলাচল-সহায়ক ও আরামদায়ক নামাজের হিজাব। মাপ অনুযায়ী ফিতা দিয়ে ছোট-বড় করা যায় এবং ফুল কাভারেজ।',
    bulletPoints: [
      'খাঁটি বেক্সি বয়েল (Bexi boil) কাপড়',
      'বাতাস চলাচল-সহায়ক ও ব্রিদেবল',
      'মাপ অনুযায়ী ছোট-বড় করা যায় (Adjustable)',
      'ফুল কাভারেজ',
      '১ পিসের দাম ৫৫০ টাকা',
    ],
    fabric: '১০০% খাঁটি বেক্সি বয়েল সুতি',
    sizes: ['ফ্রি সাইজ (এডজাস্টেবল)'],
    colors: [
      { name: 'ল্যাভেন্ডার ফ্লোরাল', hex: '#B8A4C9' },
      { name: 'মিন্ট গ্রিন ফ্লোরাল', hex: '#A3C4BC' },
      { name: 'সফট পিচ ফ্লোরাল', hex: '#F3C4B6' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 5.0,
    reviewCount: 47,
  },
  {
    id: 'tiara-prayer-hijab-mint',
    name: 'Bexi Boil Prayer Hijab - Mint Green',
    banglaName: 'বেক্সি বয়েল নামাজের হিজাব - মিন্ট গ্রিন',
    slug: 'bexi-boil-prayer-hijab-mint',
    category: 'hijab',
    price: 550,
    originalPrice: 650,
    images: [
      '/images/products/prayer-hijab-mint.jpg',
      '/images/products/prayer-hijab-all-1.jpg',
      '/images/products/prayer-hijab-all-2.jpg',
    ],
    description: 'খাঁটি বেক্সি বয়েল কাপড় দিয়ে তৈরি স্নিগ্ধ মিন্ট গ্রিন কালারের ব্রিদেবল নামাজের হিজাব। মাপ অনুযায়ী ছোট-বড় করা যায়।',
    bulletPoints: [
      'খাঁটি বেক্সি বয়েল কাপড়',
      'বাতাস চলাচল-সহায়ক ও আরামদায়ক',
      'মাপ অনুযায়ী এডজাস্টেবল',
      'ফুল কাভারেজ',
      '১ পিসের দাম ৫৫০ টাকা',
    ],
    fabric: '১০০% খাঁটি বেক্সি বয়েল সুতি',
    sizes: ['ফ্রি সাইজ (এডজাস্টেবল)'],
    colors: [
      { name: 'মিন্ট গ্রিন ফ্লোরাল', hex: '#A3C4BC' },
      { name: 'ল্যাভেন্ডার ফ্লোরাল', hex: '#B8A4C9' },
      { name: 'সফট পিচ ফ্লোরাল', hex: '#F3C4B6' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 5.0,
    reviewCount: 39,
  },
  {
    id: 'tiara-prayer-hijab-peach',
    name: 'Bexi Boil Prayer Hijab - Soft Peach',
    banglaName: 'বেক্সি বয়েল নামাজের হিজাব - সফট পিচ',
    slug: 'bexi-boil-prayer-hijab-peach',
    category: 'hijab',
    price: 550,
    originalPrice: 650,
    images: [
      '/images/products/prayer-hijab-peach.jpg',
      '/images/products/prayer-hijab-all-2.jpg',
      '/images/products/prayer-hijab-all-1.jpg',
    ],
    description: 'খাঁটি বেক্সি বয়েল কাপড় দিয়ে তৈরি মিষ্টি সফট পিচ ফ্লোরাল নামাজের হিজাব। বাতাস চলাচল-সহায়ক ও সম্পূর্ণ শালীন কাভারেজ।',
    bulletPoints: [
      'খাঁটি বেক্সি বয়েল কাপড়',
      'বাতাস চলাচল-সহায়ক ও আরামদায়ক',
      'মাপ অনুযায়ী এডজাস্টেবল',
      'ফুল কাভারেজ',
      '১ পিসের দাম ৫৫০ টাকা',
    ],
    fabric: '১০০% খাঁটি বেক্সি বয়েল সুতি',
    sizes: ['ফ্রি সাইজ (এডজাস্টেবল)'],
    colors: [
      { name: 'সফট পিচ ফ্লোরাল', hex: '#F3C4B6' },
      { name: 'ল্যাভেন্ডার ফ্লোরাল', hex: '#B8A4C9' },
      { name: 'মিন্ট গ্রিন ফ্লোরাল', hex: '#A3C4BC' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.9,
    reviewCount: 31,
  },
  {
    id: 'tiara-prayer-hijab-combo',
    name: 'Bexi Boil Prayer Hijab - 3 Colors Combo',
    banglaName: '৩ পিস বেক্সি বয়েল নামাজের হিজাব কম্বো',
    slug: 'bexi-boil-prayer-hijab-3-piece-combo',
    category: 'hijab',
    price: 1550,
    originalPrice: 1650,
    images: [
      '/images/products/prayer-hijab-all-1.jpg',
      '/images/products/prayer-hijab-all-2.jpg',
      '/images/products/prayer-hijab-lavender.jpg',
      '/images/products/prayer-hijab-mint.jpg',
      '/images/products/prayer-hijab-peach.jpg',
    ],
    description: 'ল্যাভেন্ডার, মিন্ট ও পিচ—তিনটি আকর্ষণীয় কালারের বেক্সি বয়েল নামাজের হিজাব কম্বো প্যাক।',
    bulletPoints: [
      '৩টি আকর্ষণীয় কালার সেট (ল্যাভেন্ডার, মিন্ট, পিচ)',
      'খাঁটি বেক্সি বয়েল কাপড়',
      'বাতাস চলাচল-সহায়ক ও আরামদায়ক',
      'মাপ অনুযায়ী এডজাস্টেবল',
      'কম্বো মূল্য ১৫৫০ টাকা',
    ],
    fabric: '১০০% খাঁটি বেক্সি বয়েল সুতি',
    sizes: ['৩ পিস ফ্রি সাইজ'],
    colors: [
      { name: '৩ কালার কম্বো সেট', hex: '#A3C4BC' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 5.0,
    reviewCount: 58,
  },

  // --- Category: INNER CAP ---
  {
    id: 'tiara-lace-inner-cap',
    name: 'Breathable Lace Inner Cap',
    banglaName: 'বাতাস চলাচল-উপযোগী লেইস ইনার ক্যাপ',
    slug: 'breathable-lace-inner-cap',
    category: 'inner-cap',
    price: 80,
    originalPrice: 100,
    images: [
      '/images/products/inner-cap-lace.jpg',
    ],
    description: 'বাতাস চলাচল-উপযোগী লেইসের ইনার ক্যাপ। লেইস দিয়ে তৈরি, প্রসারনযোগ্য ও হিজাব ঠিক জায়গায় স্থির রাখতে সহায়ক। ১টির দাম ৮০ টাকা, ২টি ১৫০ টাকা।',
    bulletPoints: [
      'লেইস দিয়ে তৈরি',
      'প্রসারনযোগ্য ও বাতাস চলাচল-উপযোগী',
      'হিজাব ঠিক জায়গায় স্থির থাকে',
      '১টি ৮০ টাকা | ২টি ১৫০ টাকা',
      'চাঁদপুর সদর ৫০৳ | ঢাকা ১২০৳',
    ],
    fabric: 'প্রিমিয়াম প্রসারনযোগ্য লেইস',
    sizes: ['ফ্রি সাইজ'],
    colors: [
      { name: 'ডিপ গ্রিন (Deep Green)', hex: '#234E3E' },
      { name: 'ব্ল্যাক (Black)', hex: '#1A1A1A' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 5.0,
    reviewCount: 24,
  },

  // --- Category: HIJAB PINS ---
  {
    id: 'tiara-dressmaker-hijab-pins',
    name: 'Stainless Steel Ball Hijab Pins',
    banglaName: 'স্টেইনলেস স্টিল বল হিজাব পিন বক্স',
    slug: 'stainless-steel-hijab-pins',
    category: 'hijab-pins',
    price: 80,
    originalPrice: 100,
    images: [
      '/images/products/hijab-pins.jpg',
    ],
    description: 'মসৃণ ও প্রিমিয়াম স্টেইনলেস স্টিল হেড বল পিন। কাপড়ে কোনো দাগ ফেলে না বা সুতো টানে না। নিরাপদ প্লাস্টিক বক্স সহ।',
    bulletPoints: [
      'স্টেইনলেস স্টিল মেটেরিয়াল',
      'কাপড়ে দাগ পড়ে না ও মসৃণ',
      'প্লাস্টিক স্টোরেজ বক্স সহ',
      'চাঁদপুর সদর ৫০৳ | ঢাকা ১২০৳',
    ],
    fabric: 'স্টেইনলেস স্টিল',
    sizes: ['১ বক্স'],
    colors: [
      { name: 'গোল্ডেন (Gold)', hex: '#D4AF37' },
      { name: 'সিলভার (Silver)', hex: '#C0C0C0' },
      { name: 'রোজ গোল্ড (Rose Gold)', hex: '#B76E79' },
      { name: 'গানমেটাল (Gunmetal)', hex: '#4A4A4A' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 5.0,
    reviewCount: 19,
  },
];
