import { Category, Product, CustomerReview, ReelVideo } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: 'abayas',
    name: 'Abayas & Borka',
    banglaName: 'বোরকা ও আবায়া',
    slug: 'abayas',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=600&auto=format&fit=crop',
    itemCount: 42,
    description: 'প্রিমিয়াম দুবাই চেরি ও নিদা ফেব্রিকের এক্সক্লুসিভ আবায়া কালেকশন',
  },
  {
    id: 'gowns',
    name: 'Festive Gowns',
    banglaName: 'ফেস্টিভ গাউন',
    slug: 'gowns',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=600&auto=format&fit=crop',
    itemCount: 28,
    description: 'অনুষ্ঠান ও বিশেষ দিনের জন্য নিখুঁত কারচুপির কাজ করা রাজকীয় গাউন',
  },
  {
    id: 'hijabs',
    name: 'Hijabs & Khimars',
    banglaName: 'হিজাব ও খিমার',
    slug: 'hijabs',
    image: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=600&auto=format&fit=crop',
    itemCount: 35,
    description: 'সফট প্রিমিয়াম শিফন, ক্রেপ এবং আরামদায়ক খিমার সেট',
  },
  {
    id: 'coords',
    name: 'Co-ord Sets',
    banglaName: 'কো-অর্ড সেট',
    slug: 'coords',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=600&auto=format&fit=crop',
    itemCount: 19,
    description: 'দৈনন্দিন ব্যবহারের জন্য শালীন ও স্টাইলিশ টু-পিস কো-অর্ড সেট',
  },
  {
    id: 'kurtis',
    name: 'Modest Tops & Kurti',
    banglaName: 'শালীন কুর্তি ও টপস',
    slug: 'kurtis',
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=600&auto=format&fit=crop',
    itemCount: 24,
    description: 'সহজ ও আরামদায়ক লং কুর্তি ও শ্রাগ ডিজাইন',
  },
  {
    id: 'accessories',
    name: 'Accessories & Pins',
    banglaName: 'এক্সেসরিজ ও পিন',
    slug: 'accessories',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600&auto=format&fit=crop',
    itemCount: 16,
    description: 'ম্যাগনেটিক পিন, ব্রোচ ও সিগনেচার টিয়ারা জুয়েলারি',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'tiara-abaya-01',
    name: 'Zahira Dubai Cherry Silk Abaya',
    banglaName: 'জাহিরা দুবাই চেরি সিল্ক আবায়া',
    slug: 'zahira-dubai-cherry-silk-abaya',
    category: 'abayas',
    price: 3450,
    originalPrice: 4200,
    discountBadge: '18% OFF',
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'দুবাই প্রিমিয়াম চেরি জর্জেট ফেব্রিকের তৈরি রাজকীয় ফ্লেয়ারড আবায়া। স্লিভসে নিখুঁত কারচুপির সূচিকর্ম এবং সাথে ফ্রন্ট বাটন ডিটেইলিং। গরম ও ঠান্ডায় পরার জন্য অত্যন্ত আরামদায়ক।',
    fabric: 'Original Dubai Cherry Georgette with Silk Blend',
    sizes: ['52', '54', '56'],
    colors: [
      { name: 'Royal Burgundy', hex: '#5B1026' },
      { name: 'Petal Rose', hex: '#F7D6DE' },
      { name: 'Midnight Black', hex: '#1C191A' },
      { name: 'Muted Mauve', hex: '#936D78' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    isEidArrival: true,
    rating: 4.9,
    reviewCount: 38,
  },
  {
    id: 'tiara-gown-01',
    name: 'Noor Handwork Organza Festive Gown',
    banglaName: 'নূর হ্যান্ডওয়ার্ক অরগানজা ফেস্টিভ গাউন',
    slug: 'noor-handwork-organza-festive-gown',
    category: 'gowns',
    price: 4650,
    originalPrice: 5500,
    discountBadge: '15% OFF',
    images: [
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'ঈদ ও বিয়ের অনুষ্ঠানের জন্য প্রিমিয়াম গ্লাস টিস্যু অরগানজা গাউন। গলার কাছে ও হাতায় জারদৌসি ও কাটদানার হ্যান্ডওয়ার্ক। ভেতরের সফট বাটার সিল্ক ইনার দেওয়া আছে।',
    fabric: 'Luxury Pure Organza with Silk Lining',
    sizes: ['52', '54', '56'],
    colors: [
      { name: 'Blush Rose Gold', hex: '#E6B8C2' },
      { name: 'Deep Wine', hex: '#5B1026' },
      { name: 'Champagne Beige', hex: '#E7D8C9' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    isEidArrival: true,
    rating: 5.0,
    reviewCount: 29,
  },
  {
    id: 'tiara-abaya-02',
    name: 'Mahira Karchupi Premium Nida Abaya',
    banglaName: 'মাহিরা কারচুপি প্রিমিয়াম নিদা আবায়া',
    slug: 'mahira-karchupi-premium-nida-abaya',
    category: 'abayas',
    price: 3850,
    originalPrice: 4500,
    discountBadge: '14% OFF',
    images: [
      'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'সৌদি অরিজিনাল নিদা কাপড়ে তৈরি বিলাসবহুল কারচুপি আবায়া। হাতায় চমৎকার ফ্লোরাল মোটিফের এমব্রয়ডারি ও ক্রিস্টাল পাথর বসানো। কাটিং অত্যন্ত মার্জিত ও শালীন।',
    fabric: 'Authentic Saudi Nida Soft Matte',
    sizes: ['52', '54', '56'],
    colors: [
      { name: 'Deep Wine', hex: '#5B1026' },
      { name: 'Jet Black', hex: '#111111' },
      { name: 'Sage Olive', hex: '#687563' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    isEidArrival: true,
    rating: 4.8,
    reviewCount: 44,
  },
  {
    id: 'tiara-coord-01',
    name: 'Aisha Pure Linen Modest Co-ord Set',
    banglaName: 'আয়েশা পিওর লিনেন টু-পিস কো-অর্ড সেট',
    slug: 'aisha-pure-linen-modest-coord-set',
    category: 'coords',
    price: 2750,
    originalPrice: 3200,
    discountBadge: '14% OFF',
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'দৈনন্দিন অফিস, ভার্সিটি ও ভ্রমণের জন্য সেরা টু-পিস সেট। সাথে ম্যাচিং প্যান্ট ও লং ওভারসাইজড কিমোনো শার্ট। অত্যন্ত নিঃশ্বাস-যোগ্য পিওর অরগানিক লিনেন ফেব্রিক।',
    fabric: '100% Breathable Organic Washed Linen',
    sizes: ['S (36)', 'M (38)', 'L (40)', 'XL (42)'],
    colors: [
      { name: 'Tiara Dusty Rose', hex: '#E8B4C0' },
      { name: 'Warm Taupe', hex: '#B8A399' },
      { name: 'Forest Moss', hex: '#4A5B4E' },
    ],
    inStock: true,
    isFeatured: false,
    isTrending: true,
    isEidArrival: false,
    rating: 4.9,
    reviewCount: 19,
  },
  {
    id: 'tiara-hijab-01',
    name: 'Rawan French Chiffon 2-Piece Khimar',
    banglaName: 'রাওয়ান ফ্রেঞ্চ শিফন টু-পিস খিমার সেট',
    slug: 'rawan-french-chiffon-2-piece-khimar',
    category: 'hijabs',
    price: 1850,
    originalPrice: 2200,
    discountBadge: '16% OFF',
    images: [
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'মাথা ও বুক সম্পূর্ণ শালীনভাবে আবৃত রাখার জন্য ফ্লোয়িং ফ্রেঞ্চ শিফন খিমার এবং ম্যাচিং সফট স্কার্ট। বাতাসে ওড়ে না, মাথায় স্লিপ খায় না।',
    fabric: 'High-Density Non-Slip French Chiffon',
    sizes: ['Free Size (Front 45", Back 55")'],
    colors: [
      { name: 'Burgundy Wine', hex: '#5B1026' },
      { name: 'Rose Petal', hex: '#F7D6DE' },
      { name: 'Desert Camel', hex: '#C29B7F' },
      { name: 'Charcoal Black', hex: '#222222' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: false,
    isEidArrival: true,
    rating: 4.9,
    reviewCount: 52,
  },
  {
    id: 'tiara-abaya-03',
    name: 'Tasneem Two-Tone Cape Abaya',
    banglaName: 'তাসনীম টু-টোন কেপ আবায়া',
    slug: 'tasneem-two-tone-cape-abaya',
    category: 'abayas',
    price: 3650,
    originalPrice: 4400,
    discountBadge: '17% OFF',
    images: [
      'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'আধুনিক কেপ স্টাইলের টু-টোন আবায়া। সাথে ফ্রন্ট টাই-আপ বেল্ট। যে কোনো গায়ের রঙে দারুণ মানিয়ে যায়।',
    fabric: 'Dubai Georgette & Satin Weave',
    sizes: ['52', '54', '56'],
    colors: [
      { name: 'Blush Pink & Burgundy', hex: '#8C2844' },
      { name: 'Mocha & Cream', hex: '#9E7E6B' },
    ],
    inStock: true,
    isFeatured: false,
    isTrending: true,
    isEidArrival: true,
    rating: 4.7,
    reviewCount: 22,
  },
  {
    id: 'tiara-gown-02',
    name: 'Ruqayya Embroidered Modest Gown',
    banglaName: 'রুকাইয়া এমব্রয়ডার্ড মডেস্ট গাউন',
    slug: 'ruqayya-embroidered-modest-gown',
    category: 'gowns',
    price: 4950,
    originalPrice: 5800,
    discountBadge: '15% OFF',
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'গোল্ডেন জরি ও সুতার নিখুঁত এমব্রয়ডারি সহ প্রিমিয়াম সফট জর্জেট গাউন। সুন্দর প্লিটেড ঘের ও আরামদায়ক কাটিং।',
    fabric: 'Georgette Silk with Gold Threadwork',
    sizes: ['52', '54', '56'],
    colors: [
      { name: 'Deep Burgundy Wine', hex: '#5B1026' },
      { name: 'Emerald Forest', hex: '#1E3F2D' },
      { name: 'Pearl Cream', hex: '#F7F3E9' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: false,
    isEidArrival: true,
    rating: 5.0,
    reviewCount: 31,
  },
  {
    id: 'tiara-kurti-01',
    name: 'Safa Modest Flowing Long Kurti',
    banglaName: 'সাফা মডেস্ট ফ্লোয়িং লং কুর্তি',
    slug: 'safa-modest-flowing-long-kurti',
    category: 'kurtis',
    price: 2150,
    originalPrice: 2600,
    discountBadge: '17% OFF',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'শালীন দৈর্ঘ্যের এ-লাইন ফ্লোয়িং কুর্তি। বাটন ফ্রন্ট ও আরামদায়ক কাটিং। জিন্স বা পালাজ্জোর সাথে পরার জন্য চমৎকার।',
    fabric: 'Soft Rayon Slub Cotton',
    sizes: ['38', '40', '42', '44'],
    colors: [
      { name: 'Rose Plum', hex: '#873B52' },
      { name: 'Soft Cream', hex: '#F9F4EB' },
      { name: 'Steel Blue', hex: '#486278' },
    ],
    inStock: true,
    isFeatured: false,
    isTrending: true,
    isEidArrival: false,
    rating: 4.8,
    reviewCount: 17,
  },
];

export const REVIEWS: CustomerReview[] = [
  {
    id: 'rev-1',
    author: 'সানজিদা ইসলাম চৌধুরী',
    city: 'ধানমন্ডি, ঢাকা',
    rating: 5,
    comment: 'আলহামদুলিল্লাহ! টিয়ারার জাহিরা আবায়াটা হাতে পেয়ে মুগ্ধ হয়ে গেলাম। ফেব্রিকটা এতো সফট আর আরামদায়ক যে গরমেও পরা যায়। ডেলিভারিও মাত্র ২৪ ঘণ্টার মধ্যে পেয়েছি।',
    date: '৩ দিন আগে',
    productName: 'Zahira Dubai Cherry Silk Abaya',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop',
  },
  {
    id: 'rev-2',
    author: 'নুসরাত জাহান তন্বী',
    city: 'জিইসি মোড়, চট্টগ্রাম',
    rating: 5,
    comment: 'নূর ফেস্টিভ গাউনটা বোনের বিয়ের জন্য নিয়েছিলাম। ছবি থেকে বাস্তবে দেখতে আরও ১০০ গুণ সুন্দর ও লাক্সারি! সাইজ একদম পারফেক্ট ছিল। ক্যাশ অন ডেলিভারিতে অর্ডার করতে পেরে কোনো ঝামেলা ছাড়াই কাজ হয়ে গেল।',
    date: '১ সপ্তাহ আগে',
    productName: 'Noor Handwork Organza Gown',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=150&auto=format&fit=crop',
  },
  {
    id: 'rev-3',
    author: 'ফারহানা আহমেদ',
    city: 'উপশহর, সিলেট',
    rating: 5,
    comment: 'টিয়ারার কালার কম্বিনেশন আর কাপড়ের ফিনিশিং চোখ জুড়িয়ে যায়। খিমার সেটের ফ্যাব্রিকটা এতো প্রিমিয়াম যে মাথায় পিছলে যায় না। মেসেঞ্জারেও আপুরা খুব দ্রুত রিপ্লাই দিয়েছেন।',
    date: '২ সপ্তাহ আগে',
    productName: 'Rawan French Chiffon Khimar',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=150&auto=format&fit=crop',
  },
  {
    id: 'rev-4',
    author: 'সুমাইয়া আক্তার রিফাহ',
    city: 'উত্তরা, ঢাকা',
    rating: 5,
    comment: 'কারচুপির কাজটা এতো নিখুঁত হবে আশা করিনি। সাধারণ অনলাইন পেজগুলোতে ছবি আর প্রোডাক্টের তফাত থাকে, কিন্তু টিয়ারার প্রোডাক্ট পুরো ছবির মতোই নিখুঁত। ধন্যবাদ টিয়ারা টিম!',
    date: '১০ দিন আগে',
    productName: 'Mahira Karchupi Nida Abaya',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=150&auto=format&fit=crop',
  },
];

export const REELS: ReelVideo[] = [
  {
    id: 'reel-1',
    title: 'Zahira Abaya in Movement & Flare',
    banglaTitle: 'জাহিরা আবায়ার ফ্লেয়ার ও কারচুপি লুক',
    productId: 'tiara-abaya-01',
    thumbnail: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=600&auto=format&fit=crop',
    videoDuration: '0:28',
    views: '18.4K',
    price: 3450,
  },
  {
    id: 'reel-2',
    title: 'Noor Festive Gown Glitz & Sparkle',
    banglaTitle: 'নূর ফেস্টিভ গাউনের গর্জিয়াস জারদৌসি ওয়ার্ক',
    productId: 'tiara-gown-01',
    thumbnail: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=600&auto=format&fit=crop',
    videoDuration: '0:34',
    views: '24.9K',
    price: 4650,
  },
  {
    id: 'reel-3',
    title: 'How to Style Rawan Chiffon Khimar',
    banglaTitle: 'রাওয়ান ফ্রেঞ্চ শিফন খিমার স্টাইলিং গাইড',
    productId: 'tiara-hijab-01',
    thumbnail: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=600&auto=format&fit=crop',
    videoDuration: '0:42',
    views: '31.2K',
    price: 1850,
  },
  {
    id: 'reel-4',
    title: 'Aisha Linen Modest Co-ord Real Review',
    banglaTitle: 'আয়েশা লিনেন কো-অর্ড সেট আনবক্সিং',
    productId: 'tiara-coord-01',
    thumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=600&auto=format&fit=crop',
    videoDuration: '0:22',
    views: '14.1K',
    price: 2750,
  },
];
