import { Category, Product, CustomerReview } from '@/types';

export const FB_PROFILE_URL = 'https://www.facebook.com/profile.php?id=61594225684008';
export const MESSENGER_URL = 'https://m.me/61594225684008';

export const CATEGORIES: Category[] = [
  {
    id: 'prayer-hijab',
    name: 'Prayer Hijab',
    banglaName: 'নামাজের হিজাব',
    slug: 'prayer-hijab',
    image: '/images/products/prayer-hijab-all-1.jpg',
    itemCount: 4,
    description: 'খাঁটি বেক্সি বয়েল (Bexi boil) কাপড়ে তৈরি আরামদায়ক ও ফুল কাভারেজ নামাজের হিজাব',
  },
  {
    id: 'inner-cap',
    name: 'Inner Cap',
    banglaName: 'ইনার ক্যাপ',
    slug: 'inner-cap',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=600&auto=format&fit=crop',
    itemCount: 2,
    description: 'চুল ও হিজাব সঠিকভাবে ধরে রাখার জন্য সফট ব্রিদেবল কটন ইনার ক্যাপ',
  },
  {
    id: 'hijab-pins',
    name: 'Hijab Pins',
    banglaName: 'হিজাব পিন',
    slug: 'hijab-pins',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600&auto=format&fit=crop',
    itemCount: 2,
    description: 'কাপড় নষ্ট না করে শক্তভাবে আটকে রাখার নো-স্ন্যাগ ম্যাগনেটিক হিজাব পিন',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'tiara-prayer-hijab-lavender',
    name: 'Breathable Bexi Boil Prayer Hijab - Lavender',
    banglaName: 'বেক্সি বয়েল নামাজের হিজাব - ল্যাভেন্ডার ফ্লোরাল',
    slug: 'bexi-boil-prayer-hijab-lavender',
    category: 'prayer-hijab',
    price: 550,
    originalPrice: 650,
    discountBadge: '১০০% খাঁটি বেক্সি',
    images: [
      '/images/products/prayer-hijab-lavender.jpg',
      '/images/products/prayer-hijab-all-1.jpg',
      '/images/products/prayer-hijab-all-2.jpg',
    ],
    description: '🌷 নামাজের জন্য আরামদায়ক ও বাতাস চলাচল-সহায়ক হিজাব 🌷\nখাঁটি বেক্সি বয়েল (Bexi boil) কাপড় দিয়ে যত্নসহকারে তৈরি। বাতাস চলাচল করে বিধায় গরমেও আরামদায়ক এবং মাপ অনুযায়ী ফিতা দিয়ে ছোট-বড় (Adjustable) করা যায়। সম্পূর্ণ শালীন ফুল কাভারেজ।',
    bulletPoints: [
      'খাঁটি বেক্সি বয়েল (Bexi boil) কাপড় দিয়ে তৈরি ✔️',
      'বাতাস চলাচল-সহায়ক (Breathable) ✔️',
      'মাপ অনুযায়ী ছোট-বড় করা যায় (Adjustable) ✔️',
      'ফুল কাভারেজ (Full Coverage) ✔️',
      '১ পিসের দাম ৫৫০ টাকা 💵',
      'চাঁদপুরে ডেলিভারি চার্জ ৫০ টাকা {চাঁদপুর সদর} 📦',
      'ঢাকায় ডেলিভারি চার্জ ১২০ টাকা 📦',
    ],
    fabric: '১০০% খাঁটি বেক্সি বয়েল (Pure Bexi Boil Cotton)',
    sizes: ['ফ্রি সাইজ (এডজাস্টেবল ফিতা সহ)'],
    colors: [
      { name: 'ল্যাভেন্ডার পার্পল ফ্লোরাল', hex: '#B8A4C9' },
      { name: 'মিন্ট গ্রিন ফ্লোরাল', hex: '#A3C4BC' },
      { name: 'সফট পিচ ফ্লোরাল', hex: '#F3C4B6' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 5.0,
    reviewCount: 47,
  },
  {
    id: 'tiara-prayer-hijab-mint',
    name: 'Breathable Bexi Boil Prayer Hijab - Mint Green',
    banglaName: 'বেক্সি বয়েল নামাজের হিজাব - মিন্ট গ্রিন ফ্লোরাল',
    slug: 'bexi-boil-prayer-hijab-mint',
    category: 'prayer-hijab',
    price: 550,
    originalPrice: 650,
    discountBadge: '১০০% খাঁটি বেক্সি',
    images: [
      '/images/products/prayer-hijab-mint.jpg',
      '/images/products/prayer-hijab-all-1.jpg',
      '/images/products/prayer-hijab-all-2.jpg',
    ],
    description: '🌷 নামাজের জন্য আরামদায়ক ও বাতাস চলাচল-সহায়ক হিজাব 🌷\nখাঁটি বেক্সি বয়েল (Bexi boil) কাপড় দিয়ে তৈরি। বাতাস চলাচল-সহায়ক (Breathable), মাপ অনুযায়ী ছোট-বড় করা যায় (Adjustable) এবং ফুল কাভারেজ। নামাজে প্রশান্তিময় অনুভূতির জন্য সেরা পছন্দ।',
    bulletPoints: [
      'খাঁটি বেক্সি বয়েল (Bexi boil) কাপড় দিয়ে তৈরি ✔️',
      'বাতাস চলাচল-সহায়ক (Breathable) ✔️',
      'মাপ অনুযায়ী ছোট-বড় করা যায় (Adjustable) ✔️',
      'ফুল কাভারেজ (Full Coverage) ✔️',
      '১ পিসের দাম ৫৫০ টাকা 💵',
      'চাঁদপুরে ডেলিভারি ৫০ টাকা | ঢাকায় ডেলিভারি ১২০ টাকা',
    ],
    fabric: '১০০% খাঁটি বেক্সি বয়েল (Pure Bexi Boil Cotton)',
    sizes: ['ফ্রি সাইজ (এডজাস্টেবল ফিতা সহ)'],
    colors: [
      { name: 'মিন্ট গ্রিন ফ্লোরাল', hex: '#A3C4BC' },
      { name: 'ল্যাভেন্ডার পার্পল ফ্লোরাল', hex: '#B8A4C9' },
      { name: 'সফট পিচ ফ্লোরাল', hex: '#F3C4B6' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 5.0,
    reviewCount: 39,
  },
  {
    id: 'tiara-prayer-hijab-peach',
    name: 'Breathable Bexi Boil Prayer Hijab - Soft Peach',
    banglaName: 'বেক্সি বয়েল নামাজের হিজাব - সফট পিচ ফ্লোরাল',
    slug: 'bexi-boil-prayer-hijab-peach',
    category: 'prayer-hijab',
    price: 550,
    originalPrice: 650,
    discountBadge: '১০০% খাঁটি বেক্সি',
    images: [
      '/images/products/prayer-hijab-peach.jpg',
      '/images/products/prayer-hijab-all-2.jpg',
      '/images/products/prayer-hijab-all-1.jpg',
    ],
    description: '🌷 নামাজের জন্য আরামদায়ক ও বাতাস চলাচল-সহায়ক হিজাব 🌷\nখাঁটি বেক্সি বয়েল (Bexi boil) কাপড় দিয়ে তৈরি। বাতাস চলাচল-সহায়ক (Breathable), মাপ অনুযায়ী ছোট-বড় করা যায় (Adjustable) এবং ফুল কাভারেজ। পরতে ও ধুতে খুব সহজ।',
    bulletPoints: [
      'খাঁটি বেক্সি বয়েল (Bexi boil) কাপড় দিয়ে তৈরি ✔️',
      'বাতাস চলাচল-সহায়ক (Breathable) ✔️',
      'মাপ অনুযায়ী ছোট-বড় করা যায় (Adjustable) ✔️',
      'ফুল কাভারেজ (Full Coverage) ✔️',
      '১ পিসের দাম ৫৫০ টাকা 💵',
      'চাঁদপুরে ডেলিভারি ৫০ টাকা | ঢাকায় ডেলিভারি ১২০ টাকা',
    ],
    fabric: '১০০% খাঁটি বেক্সি বয়েল (Pure Bexi Boil Cotton)',
    sizes: ['ফ্রি সাইজ (এডজাস্টেবল ফিতা সহ)'],
    colors: [
      { name: 'সফট পিচ ফ্লোরাল', hex: '#F3C4B6' },
      { name: 'ল্যাভেন্ডার পার্পল ফ্লোরাল', hex: '#B8A4C9' },
      { name: 'মিন্ট গ্রিন ফ্লোরাল', hex: '#A3C4BC' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.9,
    reviewCount: 31,
  },
  {
    id: 'tiara-prayer-hijab-combo',
    name: 'Bexi Boil Prayer Hijab - 3 Colors Combo Pack',
    banglaName: '৩ পিস বেক্সি বয়েল নামাজের হিজাব স্পেশাল কম্বো',
    slug: 'bexi-boil-prayer-hijab-3-piece-combo',
    category: 'prayer-hijab',
    price: 1550,
    originalPrice: 1650,
    discountBadge: '১০০৳ ছাড় + স্পেশাল অফার',
    images: [
      '/images/products/prayer-hijab-all-1.jpg',
      '/images/products/prayer-hijab-all-2.jpg',
      '/images/products/prayer-hijab-lavender.jpg',
      '/images/products/prayer-hijab-mint.jpg',
      '/images/products/prayer-hijab-peach.jpg',
    ],
    description: 'ল্যাভেন্ডার, মিন্ট গ্রিন ও সফট পিচ—তিনটি আকর্ষণীয় কালারের বেক্সি বয়েল নামাজের হিজাবের স্পেশাল কম্বো প্যাক। খাঁটি বেক্সি বয়েল, বাতাস চলাচল সহায়ক এবং মাপ অনুযায়ী ফিতা দিয়ে এডজাস্টেবল। উপহার দেওয়ার জন্য চমৎকার।',
    bulletPoints: [
      '৩টি সম্পূর্ণ ভিন্ন ও মিষ্টি কালার (ল্যাভেন্ডার, মিন্ট, পিচ)',
      'খাঁটি বেক্সি বয়েল (Bexi boil) কাপড় দিয়ে তৈরি ✔️',
      'বাতাস চলাচল-সহায়ক ও পরম আরামদায়ক ✔️',
      'মাপ অনুযায়ী ছোট-বড় করা যায় ✔️',
      'ফুল কাভারেজ ও শালীন ডিজাইন ✔️',
    ],
    fabric: '১০০% খাঁটি বেক্সি বয়েল (Pure Bexi Boil Cotton)',
    sizes: ['৩ পিস ফ্রি সাইজ (এডজাস্টেবল)'],
    colors: [
      { name: '৩ কালার কম্বো সেট', hex: '#A3C4BC' },
    ],
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 5.0,
    reviewCount: 58,
  },
  {
    id: 'tiara-inner-cap-cotton',
    name: 'Premium Breathable Stretch Cotton Inner Cap',
    banglaName: 'প্রিমিয়াম ব্রিদেবল কটন ইনার ক্যাপ',
    slug: 'premium-breathable-stretch-cotton-inner-cap',
    category: 'inner-cap',
    price: 120,
    originalPrice: 150,
    discountBadge: 'সফট কটন',
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'নামাজের হিজাব ও সাধারণ হিজাব যেন মাথায় পিছলে না যায় সেজন্য প্রিমিয়াম সফট স্ট্রেচ কটন ইনার ক্যাপ। বাতাস চলাচল করে ও সারাদিন পরে থাকলেও মাথায় ব্যাথা হয় না।',
    bulletPoints: [
      'সফট ১০০% ব্রিদেবল স্ট্রেচ কটন',
      'মাথায় পিছলে যায় না ও কপালে দাগ বসে না',
      'ঘাম শোষণ করে ও আরামদায়ক',
      'ফ্রি সাইজ (সব বয়সের জন্য প্রযোজ্য)',
    ],
    fabric: 'Organic Breathable Stretch Cotton',
    sizes: ['ফ্রি সাইজ (Elastic Stretch)'],
    colors: [
      { name: 'জেট ব্ল্যাক', hex: '#111111' },
      { name: 'নুড বেইজ', hex: '#E7D8C9' },
      { name: 'সফট হোয়াইট', hex: '#FFFFFF' },
      { name: 'ডিপ মেরুন', hex: '#590F23' },
    ],
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.9,
    reviewCount: 23,
  },
  {
    id: 'tiara-magnetic-hijab-pins',
    name: 'Snag-Free Strong Magnetic Hijab Pins (Set of 4)',
    banglaName: 'নো-স্ন্যাগ স্ট্রং ম্যাগনেটিক হিজাব পিন (৪ পিস সেট)',
    slug: 'snag-free-magnetic-hijab-pins-set',
    category: 'hijab-pins',
    price: 180,
    originalPrice: 240,
    discountBadge: 'কাপড় নষ্ট হয় না',
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'সাধারণ সেফটি পিন ব্যবহারে বেক্সি বয়েল বা সুতি কাপড়ে ছিদ্র হয়ে কাপড় নষ্ট হয়। এই আল্ট্রা-স্ট্রং ম্যাগনেটিক পিন কাপড় ফুটো না করেই শক্তভাবে হিজাব আটকে রাখে।',
    bulletPoints: [
      'কাপড়ে কোনো ফুটো বা সুতা টানে না (Snag-Free)',
      'আল্ট্রা স্ট্রং নিওডিমিয়াম ম্যাগনেট',
      '৪টি ক্লাসি কালার (রোজ গোল্ড, সিলভার, গোল্ড, ম্যাট ব্ল্যাক)',
      'নামাজের সময় হিজাব ঠিক রাখতে অত্যন্ত সহায়ক',
    ],
    fabric: 'Rust-Proof High Polish Metal with Strong Magnet',
    sizes: ['৪ পিস সেট'],
    colors: [
      { name: 'মেটালিক মিক্স সেট', hex: '#C68E4D' },
    ],
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 5.0,
    reviewCount: 34,
  },
];

export const REVIEWS: CustomerReview[] = [
  {
    id: 'rev-1',
    author: 'উম্মে কুলসুম',
    city: 'চাঁদপুর সদর, চাঁদপুর',
    rating: 5,
    comment: 'আলহামদুলিল্লাহ! চাঁদপুরে অর্ডার করার পরের দিনই হিজাবটা হাতে পেয়েছি। কাপড়ের মান সত্যি অসাধারণ, খাঁটি বেক্সি বয়েল। নামাজে এতো আরাম আগে কোনো হিজাবে পাইনি।',
    date: '২ দিন আগে',
    productName: 'বেক্সি বয়েল নামাজের হিজাব - ল্যাভেন্ডার',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop',
  },
  {
    id: 'rev-2',
    author: 'ফাতেমা তুজ জোহরা',
    city: 'মিরপুর, ঢাকা',
    rating: 5,
    comment: 'ঢাকার গরমে নামাজের জন্য এমন আরামদায়ক ও ব্রিদেবল হিজাব খুঁজছিলাম। ফিতা দিয়ে মাথার মাপ অনুযায়ী এডজাস্ট করা যায় এটাই সবচেয়ে বড় সুবিধা। ৩টা কালারের কম্বোটাই নিয়ে নিলাম!',
    date: '৫ দিন আগে',
    productName: '৩ পিস বেক্সি বয়েল নামাজের হিজাব কম্বো',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=150&auto=format&fit=crop',
  },
  {
    id: 'rev-3',
    author: 'রাবেয়া সুলতানা',
    city: 'ফরিদগঞ্জ, চাঁদপুর',
    rating: 5,
    comment: 'মিন্ট কালারটা দেখতে অনেক স্নিগ্ধ আর মিষ্টি। কাপড়টা খুবই নরম আর বাতাস চলাচল করে। সেলার আপু মেসেঞ্জারে খুব দ্রুত রেসপন্স করেছেন। জাযাকাল্লাহু খাইরান।',
    date: '১ সপ্তাহ আগে',
    productName: 'বেক্সি বয়েল নামাজের হিজাব - মিন্ট গ্রিন',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=150&auto=format&fit=crop',
  },
];
